#
# Toker
#
export ZSH="/root/.oh-my-zsh"
export PS1="%d %% "
export LC_ALL=en_US.UTF-8 

ZSH_THEME="robbyrussell"
DISABLE_UPDATE_PROMPT="true"
HIST_STAMPS="yyyy/mm/dd"
source $ZSH/oh-my-zsh.sh

plugins=(git)

cd /

bash /toker/files/conf.d/aliases.sh